### ISSUE TITLE
Sometimes notes disappear

### ISSUE THREAD

**Issue by underswing** [legoandmars/BeatSaberCustomNotes#24] opened 2020-12-05 12:31 UTC
I have the problem, that in some levels some notes randomly disappear. I actually don't know if that's a custom notes issue but I never had it before installing custom notes. It also only happens when I use some custom notes. If I use the Default preset, this never happens. Would be happy if theres a fix for that

**Comment by legoandmars** [comment] 2020-12-07 13:34
known issue, duplicate of #23

**Closed as completed by legoandmars** 2020-12-07 13:34 UTC
