### ISSUE TITLE
Notes randomly disappearing in maps

### ISSUE THREAD

**Issue by ShanMan7** [legoandmars/BeatSaberCustomNotes#23] opened 2020-12-05 02:52 UTC
I'm not 100% sure this is a custom notes issue but other people have had the same problem and all of them have the customnotes mod. 

Sometimes notes teleport around or completely disappear when playing a map. You don't see it but it still counts as a miss if you don't hit it.

**Comment by legoandmars** [comment] 2020-12-05 03:02
do you have specific examples of maps this happens on?

**Comment by ShanMan7** [comment] 2020-12-05 03:04
I remember having problems with it on Come To Life by Nolanimations and the ranked Villain Virus. Unfortunately I don't have video of it happening but it seems to be pretty random because the next time I played villain virus it didn't happen

**Comment by legoandmars** [comment] 2020-12-05 03:05
weird, do you know what notes you were using?

also, if it glitched the last time you started the game maybe toss me your _latest.log in your Logs folder

**Comment by ShanMan7** [comment] 2020-12-05 03:11
I was using the 80% notes by sphynx

not sure if this is the right log but you can take a look 
[2020.12.03.21.24.42.log.gz](https://github.com/legoandmars/BeatSaberCustomNotes/files/5646410/2020.12.03.21.24.42.log.gz)

**Comment by legoandmars** [comment] 2020-12-05 03:30
hmm i don't think that's the one, should be named _latest.log directly in your Logs folder

**Comment by ShanMan7** [comment] 2020-12-05 03:30
[_latest.log](https://github.com/legoandmars/BeatSaberCustomNotes/files/5646432/_latest.log)

**Comment by ShanMan7** [comment] 2020-12-05 03:57
ok I managed to get an instance of this issue, there is a left hand down that didn't spawn
https://streamable.com/ruiz03

**Comment by LicensedCrime** [comment] 2020-12-05 04:30
I think its still the same issue i have reported.
You can see the problem more clearly using the uwu cubes.
They just go into the ghost note state.

I can confirm, it happens on a random spot of a map.
Especially a map with high ammount of notes.

**Comment by LicensedCrime** [comment] 2020-12-05 22:12
I could identify the problem.
The mods in conflict are CameraPlus and the newest BS Utils 1.6.5

If you delete CameraPlus or go with a lower version of BS Util, the problem seems to be gone.
Good luck finding an old release...

**Comment by ShanMan7** [comment] 2020-12-07 01:14
I deleted camerplus but it still happened :/

**Comment by LicensedCrime** [comment] 2020-12-07 07:11
Hmm weird... then maybe rng hit me hard. The last thing I ve tried, is using BS Utils 1.6.1, it works without "ghosting", but breaks my game on several maps..

and still its weird, that customnotes has no dependency on it..

**Comment by LicensedCrime** [comment] 2020-12-07 10:02
@ShanMan7 can you print a list of your current used mods here?
I have a new culprit, this time its Counters+.
The bug appears pretty much on an "on hit" event if i m not mistaken....

[Edit] 
Counters+ depends on SiraUtil 2.0.0, the latest is 2.2.0
Also on BSML 1.4.0, the latest is 1.4.2
sounds reasonable...

**Comment by legoandmars** [comment] 2020-12-07 13:34
cameraplus/bs utils should have no effect on it, you're probably just not getting the bug by coincidence when you disabled them

it looks like some sort of issue with the way the mod is using zenject, it's being looked into

**Comment by legoandmars** [comment] 2020-12-08 10:04
issue fixed in ac9de459d4e1835453791babccddb95ea59159b9, releasing 2.1.1 with the fix soon

**Closed as completed by legoandmars** 2020-12-08 10:04 UTC

**Comment by sovietspaceship2** [comment] 2021-01-10 05:48
oh god thank you for the fix, I was affected by the issue and was coincidentally using your mod as reference for an unrelated one I am making and realised this was the one causing it when reading CustomNoteController.cs. The fix is confusing me though, because https://github.com/legoandmars/BeatSaberCustomNotes/blob/ac9de459d4e1835453791babccddb95ea59159b9/CustomNotes/Managers/CustomNoteController.cs#L65 should fail if `container` is null; is that line meant to set it to null somehow? but then the true branch of the if statement you added will never execute
